name:                mctsGames
version:             0.1.0.0
github:              "githubuser/mctsGames"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/mctsGames#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall 
  - -Wno-unused-binds 
  - -Wno-unused-imports
  dependencies:
  - vector
  - vector-instances
  - random
  - containers
  - hashable  
  - haxl
  - mtl
  - data-msgpack
  - bytestring

executables:
  mctsGames-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-binds 
    - -Wno-unused-imports

    dependencies:
    - mctsGames
    - haxl
    - text
    - hashable
    - random

tests:
  mctsGames-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-binds  
    - -Wno-unused-imports

    dependencies:
    - mctsGames
